Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 4
  end

  config.vm.define "k8smaster" do |k8smaster|
    k8smaster.vm.hostname = "k8smaster"
    k8smaster.vm.network :private_network, ip: "192.168.12.100"
  end

  config.vm.network "forwarded_port", guest_ip: "192.168.12.100", guest: 8080, host: 8080, auto_correct: true
end
